# Generated by Django 5.2.8 on 2025-11-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aeronave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=50, unique=True)),
                ("fabricante", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                ("capacidad_kg", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("OPERATIVA", "Operativa"),
                            ("MANTENCION", "En mantención"),
                            ("FUERA", "Fuera de servicio"),
                        ],
                        default="OPERATIVA",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("licencia", models.CharField(max_length=50)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Piloto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("licencia", models.CharField(max_length=50)),
                ("horas_vuelo", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("origen", models.CharField(max_length=100)),
                ("destino", models.CharField(max_length=100)),
                (
                    "tipo_transporte",
                    models.CharField(
                        choices=[("TERRESTRE", "Terrestre"), ("AEREO", "Aéreo")],
                        max_length=20,
                    ),
                ),
                (
                    "duracion_estimada_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patente", models.CharField(max_length=20, unique=True)),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                ("capacidad_kg", models.PositiveIntegerField()),
                ("anio", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("MANTENCION", "En mantención"),
                            ("INACTIVO", "Inactivo"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("peso_kg", models.PositiveIntegerField()),
                ("tipo", models.CharField(blank=True, max_length=100)),
                (
                    "valor_estimado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transporte.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Despacho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_RUTA", "En ruta"),
                            ("ENTREGADO", "Entregado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "aeronave",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transporte.aeronave",
                    ),
                ),
                (
                    "carga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transporte.carga",
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transporte.conductor",
                    ),
                ),
                (
                    "piloto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transporte.piloto",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transporte.ruta",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transporte.vehiculo",
                    ),
                ),
            ],
        ),
    ]
